### ISSUE TITLE
Can not start the Configuration

### ISSUE THREAD

**Issue by jenspeterhess** [alengwenus/lcn-frontend#15]
I had integrated almost all my LCN modules before the last HASS update. This worked well via configuration.yaml.
After the last HASS update, I had remove all LCN modules from configuration.yaml. The system continues to run stably. 
I would now like to add more LCN modules and entities. Unfortunately, this does not work.
When I click on “add new devices”, I get a message that I should set up my pchk.
I tried that, but then the message “There is already a device with this IP number” appears. That's right...

What am I doing wrong? Do I have to delete everything and reinstall everything again? 

 
<img width="1048" alt="Bildschirmfoto 2024-09-07 um 18 53 37" src="https://github.com/user-attachments/assets/02427664-aedd-479e-bcf0-b19a69e038ee">

**Comment by alengwenus** [comment]
Hi @jenspeterhess 

just click on the "Configure" button next to the integration entry. That's the way how to open the configuration panel from where you can add new modules and entities.

**Comment by jenspeterhess** [comment]
Great! Very simple. THX
