### ISSUE TITLE
How to install

### ISSUE THREAD

**Issue by T4s-H4g** [alengwenus/lcn-frontend#2]
Dear alengwenus,
how to install your LCN Frontend? It looks very nice and I want to try it for my LCN installation.
I also use your "hass-addons/lcn-pchk" which is also very nice!

Best,
Thomas

**Comment by alengwenus** [comment]
Hi @T4s-H4g,
it is relatively difficult to use the [lcn-frontend](https://github.com/alengwenus/lcn-frontend) as a custom installation. There are several code changes in the Home Assistance core code necessary that go hand in hand with the integration.
I already set up a pull request for the LCN Frontend in the Home Assistant repository (https://github.com/home-assistant/core/pull/108664). As soon as it gets reviewed and merged it is available for everyone as part of Home Assistant.

However, if you know what you are doing, you could use the code changes in the PR to set up a custom component for LCN. But I would strongly recommend to wait for the PR to avoid screwing up your configuration.

**Comment by T4s-H4g** [comment]
Hi @alengwenus,
thanks for your reply. Than I will wait and hope your pull request for the LCN Frontend in the Home Assistant repository will be accepted.
Best,
Thomas
