### ISSUE TITLE
LCN integration crashes after a few days

### ISSUE THREAD

**Issue by mtessmer87** [alengwenus/lcn-frontend#35]
Hi, 

the lcn integration crashe after a few days. Most of the time the integration crashes after 2-3 days. All other HA components works at this time fine, only LCN is not available.

In the Log i can find the following error.

> 2024-11-14 08:58:11.487 ERROR (MainThread) [homeassistant] Error doing job: Task exception was never retrieved (None)
> Traceback (most recent call last):
>   File "/usr/local/lib/python3.12/site-packages/pypck/connection.py", line 106, in read_data_loop
>     data = await self.reader.readuntil(PckGenerator.TERMINATION.encode())
>            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/usr/local/lib/python3.12/asyncio/streams.py", line 660, in readuntil
>     await self._wait_for_data('readuntil')
>   File "/usr/local/lib/python3.12/asyncio/streams.py", line 545, in _wait_for_data
>     await self._waiter
>   File "/usr/local/lib/python3.12/asyncio/selector_events.py", line 1003, in _read_ready__data_received
>     data = self._sock.recv(self.max_size)
>            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> TimeoutError: [Errno 110] Operation timed out

After a HA restart, the LCN integration works again until the error occurs again.

Any idea to solve this issue?

regards

**Comment by alengwenus** [comment]
Hi @mtessmer87,
could you please move your issue to the [HomeAssistant issues](https://github.com/home-assistant/core/issues) as your issue does not seem to be related to the `lcn-frontend` package.
This also has the advantage that you can include the system info, which helps immensely with troubleshooting!
Thanks!
